#!/usr/bin/env bash
#
# Fetch the namespace prefix map the batch indexer needs, generated by the repository itself.
#
# The indexer resolves a property's namespace URI to its prefix through a static JSON file, and
# whatever that file holds becomes the entire map. The repository is the only component that
# knows every deployed model, so the map is generated from it, through the model-ns-prefix-mapping
# addon: https://github.com/AlfrescoLabs/model-ns-prefix-mapping
#
# Usage, from the repository root, with the stack running and the addon installed:
#
#   tools/fetch-prefix-map.sh > minimal/config/prefixes.json
#
# Environment:
#
#   ALFRESCO_URL       repository base URL, default http://localhost:8080
#   ALFRESCO_USER      administrator user, default admin
#   ALFRESCO_PASSWORD  administrator password, default admin
#
# Requires curl only. See docs/custom-content-models.md for installing the addon.

set -euo pipefail

ALFRESCO_URL="${ALFRESCO_URL:-http://localhost:8080}"
ALFRESCO_USER="${ALFRESCO_USER:-admin}"
ALFRESCO_PASSWORD="${ALFRESCO_PASSWORD:-admin}"

ENDPOINT="${ALFRESCO_URL%/}/alfresco/s/model/ns-prefix-map"

body="$(mktemp)"
trap 'rm -f "$body"' EXIT

if ! status="$(curl -sS -o "$body" -w '%{http_code}' \
    -u "${ALFRESCO_USER}:${ALFRESCO_PASSWORD}" "$ENDPOINT")"
then
    status="000"
fi

case "$status" in
    200) ;;
    401|403)
        echo "$ENDPOINT rejected ${ALFRESCO_USER} with HTTP $status." >&2
        echo "The endpoint requires an administrator; set ALFRESCO_USER and ALFRESCO_PASSWORD." >&2
        exit 1
        ;;
    404)
        echo "$ENDPOINT returned HTTP 404." >&2
        echo "The model-ns-prefix-mapping addon is not installed in this repository." >&2
        echo "See docs/custom-content-models.md." >&2
        exit 1
        ;;
    000)
        echo "Could not reach $ENDPOINT. Is the stack running?" >&2
        exit 1
        ;;
    *)
        echo "$ENDPOINT returned HTTP $status." >&2
        exit 1
        ;;
esac

# A repository that answers but has no dictionary loaded yet would produce a map without
# Alfresco's own namespaces, which fails the indexer's schema validation rather than just
# losing custom fields. Cheaper to catch here than in the indexer log.
for required in \
    '"http://www.alfresco.org/model/content/1.0":"cm"' \
    '"http://www.alfresco.org/model/system/1.0":"sys"'
do
    if ! grep -qF "$required" "$body"; then
        echo "Response from $ENDPOINT is missing ${required}." >&2
        echo "It is not a usable prefix map. Check the repository log." >&2
        exit 1
    fi
done

cat "$body"
echo
